# Generated by Django 2.2 on 2019-10-20 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startApp', '0002_auto_20191018_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImagePost',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profPic',
            field=models.ImageField(default='avatar.png', upload_to='profile_pics/'),
        ),
    ]
