# Generated by Django 2.2 on 2019-10-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startApp', '0003_auto_20191020_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
