# Generated by Django 2.2 on 2019-10-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startApp', '0004_auto_20191021_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={},
        ),
    ]
