# Generated by Django 2.2 on 2019-10-22 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startApp', '0005_auto_20191021_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='likes',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
