# Generated by Django 2.2 on 2019-10-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gramApp', '0004_profile_email_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
